workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.rowaidx.backbone
        XCODE_WORKSPACE: backbone_app/ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    working_directory: backbone_app
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - rowaid@novaskystories.com
        notify:
          success: true
          failure: true
