# Generated by Django 5.1.4 on 2026-04-04 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneFleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('geography', models.CharField(blank=True, max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DroneReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('remaining_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='drones.dronefleet')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_reservations', to='shows.show')),
            ],
        ),
    ]
