# Generated by Django 5.1.4 on 2026-04-04 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('rental_car', 'Rental Car')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('additional_people', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_entries', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
