# Generated by Django 5.1.4 on 2026-04-04 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidnightNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_id', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.JSONField(default=dict)),
                ('recipient_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PilotTableSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_id', models.CharField(max_length=255)),
                ('tab_name', models.CharField(default='Sheet1', max_length=255)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('row_data', models.JSONField(default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=20)),
                ('pilot_name', models.CharField(max_length=255)),
                ('field_changed', models.CharField(blank=True, max_length=255)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='integrations.pilottablesnapshot')),
            ],
        ),
    ]
