# Generated by Django 5.1.4 on 2026-04-04 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('permit', 'Permit'), ('logistics', 'Logistics'), ('design', 'Design'), ('safety', 'Safety'), ('travel', 'Travel')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='shows.show')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='actions_act_assigne_d888c2_idx'), models.Index(fields=['show', 'status'], name='actions_act_show_id_2f8756_idx')],
            },
        ),
    ]
